apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  labels:
    name: myingress
spec:
  rules:
  - host: kanban.k8s
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: ui-svc
            port: 
              number: 80

      - pathType: Prefix
        path: /api/
        backend:
          service:
            name: kanban-app
            port: 
              number: 8080

  